# Service
apiVersion: v1
kind: Service
metadata:
  name: hcm-nginx
  namespace: default
  labels:
    app: hcm-nginx
spec:
  ports:
  - name: tcp-web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hcm-nginx
  type: LoadBalancer
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hcm-nginx
  namespace: default
  labels:
    app: hcm-nginx
spec:
  template:
    metadata:
      labels:
        app: hcm-nginx
    spec:
      containers:
      - name: hcm-nginx
        image: kurts/hcm_nginx
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      imagePullSecrets:
      - name: regcred
---